name: Keep Fork Updated

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main # or your default branch

    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/mdbabumiamssm/IBE---kaggle-repository.git
        git fetch upstream

    - name: Merge Upstream Changes
      run: |
        git merge upstream/main # or upstream/master
        git push
